#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################

port: $(PORT)

db:
  type: $(DB_TYPE)
  host: $(DB_HOST)
  port: $(DB_PORT)
  user: $(DB_USER)
  pass: $(DB_PASS)
  db: $(DB_NAME)
  ssl: $(DB_SSL)
  schema: $(DB_SCHEMA)

  sslOptions:
    auto: true

ssl:
  enabled: $(SSL_ENABLED)
  port: $(SSL_PORT)
  provider: $(SSL_PROVIDER)
  format: $(SSL_FORMAT)
  key: $(SSL_KEY)
  cert: $(SSL_CERT)
  passphrase: $(SSL_PASSPHRASE)
  dhparam: $(SSL_DHPARAM)

bindIP: $(BIND_IP)
logLevel: $(LOG_LEVEL)
logFormat: $(LOG_FORMAT)
offline: $(OFFLINE_MODE)
ha: $(HA_ENABLED)
dataPath: $(DATA_PATH)
bodyParserLimit: $(BODY_PARSER_LIMIT)